<?php
/**
 * @var string $oasJsonUrl
 * @var string $basePath
 */

$initScript = <<<JS
window.onload = function() {
  window.ui = SwaggerUIBundle({
    url: "{$oasJsonUrl}",
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ]
  });
};
JS;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Swagger UI</title>
    <link rel="stylesheet" href="<?= $basePath; ?>swagger-ui/swagger-ui.css">
    <link rel="stylesheet" href="<?= $basePath; ?>swagger-ui/index.css">
</head>

<body>
    <div id="swagger-ui"></div>
    <script src="<?= $basePath; ?>swagger-ui/swagger-ui-bundle.js"></script>
    <script src="<?= $basePath; ?>swagger-ui/swagger-ui-standalone-preset.js"></script>

    <script>
        <?= $initScript; ?>
    </script>
</body>

</html>
